name: MCP Debugger CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
       
    - name: Setup vcpkg
      run: |
        if (!(Test-Path "vcpkg\bootstrap-vcpkg.bat")) {
          Write-Error "vcpkg not found! Check submodule initialization."
          exit 1
        }
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe integrate install
        
    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: |
          vcpkg/installed
          vcpkg/packages
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-
          
    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg.exe install --triplet x64-windows
        
    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cmake --build build --config Release
        
    - name: Test build artifacts
      run: |
        if (!(Test-Path "build/src/cli/Release/mcp-debugger.exe")) {
          Write-Error "Main executable not found!"
          exit 1
        }
        if (!(Test-Path "build/src/x64dbg/Release/mcp_debugger.dp64")) {
          Write-Error "Plugin not found!"
          exit 1
        }
        Write-Host "✅ All artifacts built successfully!"
        
    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mcp-debugger-${{ github.sha }}
        path: |
          build/src/cli/Release/mcp-debugger.exe
          build/src/x64dbg/Release/mcp_debugger.dp64
          build/src/cli/Release/*.dll
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/src/cli/Release/mcp-debugger.exe
          build/src/x64dbg/Release/mcp_debugger.dp64
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 